/**
 * TopBar
 *
 * TRANSPLANTED, NOT AUTHORED. Mechanically converted from
 * web/design-reference/embedded-sources/"Paper Card.dc.html" lines 1331-1506
 * (the Build screen's template). The only transformations applied are the ones
 * JSX requires: class -> className, inline style strings -> style objects,
 * SVG/HTML attribute names -> their React spellings, and every text node
 * emitted as an explicit string literal so whitespace stays byte-exact.
 *
 * Do NOT tidy the nesting, rename classes, add accessibility attributes or
 * "fix" spacing here. Improvement ideas belong in web/wiring/hardening-todo.md;
 * anything that would change appearance belongs in web/wiring/escalations.md.
 *
 * Generated by scripts/generate-build-jsx.mjs — regenerate, do not hand-edit.
 * `node scripts/generate-build-jsx.mjs --check` fails if this file drifts.
 */

export function TopBar() {
  return (
    <header
      style={{ flex: "none", height: "58px", display: "flex", alignItems: "center", gap: "14px", padding: "0 16px", borderBottom: "1px solid var(--divider)", background: "var(--topbar-bg)" }}
    >
      {"\n\n    "}
      <div
        style={{ flex: "1", minWidth: "0", display: "flex", alignItems: "center", gap: "12px" }}
      >
        {"\n      "}
        <div
          style={{ display: "flex", alignItems: "center", gap: "8px", flex: "none" }}
        >
          {"\n        "}
          <div
            className={"tb-mark"}
            style={{ width: "30px", height: "30px", marginTop: "-2px", borderRadius: "8px", display: "flex", alignItems: "center", justifyContent: "center", flex: "none" }}
          >
            {"\n          "}
            <svg
              width={"22"}
              height={"22"}
              viewBox={"0 0 32 32"}
              fill={"none"}
              strokeWidth={"2.4"}
              strokeLinejoin={"miter"}
              strokeLinecap={"butt"}
            >
              {"\n            "}
              <path
                d={"M16 4.5 L26 10.5 L26 21.5 L16 27.5 L6 21.5 L6 10.5 Z"}
              />
              {"\n            "}
              <path
                d={"M16 4.5 L16 16 M16 16 L6 21.5 M16 16 L26 21.5"}
              />
              {"\n            "}
              <circle
                cx={"16"}
                cy={"4.5"}
                r={"3.4"}
                fill={"var(--primary-fg)"}
                stroke={"none"}
              />
              {"\n            "}
              <circle
                cx={"26"}
                cy={"10.5"}
                r={"2.1"}
                fill={"var(--primary-fg)"}
                stroke={"none"}
              />
              {"\n            "}
              <circle
                cx={"26"}
                cy={"21.5"}
                r={"3"}
                fill={"var(--primary-fg)"}
                stroke={"none"}
              />
              {"\n            "}
              <circle
                cx={"16"}
                cy={"27.5"}
                r={"2.3"}
                fill={"var(--primary-fg)"}
                stroke={"none"}
              />
              {"\n            "}
              <circle
                cx={"6"}
                cy={"21.5"}
                r={"3.6"}
                fill={"var(--primary-fg)"}
                stroke={"none"}
              />
              {"\n            "}
              <circle
                cx={"6"}
                cy={"10.5"}
                r={"2.4"}
                fill={"var(--primary-fg)"}
                stroke={"none"}
              />
              {"\n            "}
              <circle
                cx={"16"}
                cy={"16"}
                r={"3.2"}
                fill={"var(--primary-fg)"}
                stroke={"none"}
              />
              {"\n          "}
            </svg>
            {"\n        "}
          </div>
          {"\n        "}
          <span
            style={{ fontFamily: "'Newsreader',serif", fontSize: "19px", fontWeight: "500", letterSpacing: "-0.01em", color: "var(--fg)" }}
          >
            {"OmniKnowledge"}
          </span>
          {"\n      "}
        </div>
        {"\n      "}
        <div
          style={{ width: "1px", height: "22px", background: "var(--border)", flex: "none" }}
        />
        {"\n      "}
        <div
          className={"tb-proj-wrap"}
          style={{ position: "relative", minWidth: "0", display: "flex" }}
        >
          {"\n      "}
          <button
            className={"tb-project dsh-2b56a642"}
            aria-haspopup={"true"}
            style={{ display: "flex", alignItems: "center", gap: "8px", minWidth: "0", padding: "6px 9px", border: "none", background: "transparent", borderRadius: "9px", cursor: "pointer", fontFamily: "inherit", color: "var(--fg)" }}
          >
            {"\n        "}
            <span
              style={{ width: "22px", height: "22px", borderRadius: "6px", background: "var(--card)", border: "1px solid var(--border)", display: "flex", alignItems: "center", justifyContent: "center", flex: "none" }}
            >
              {"\n          "}
              <svg
                width={"12"}
                height={"12"}
                viewBox={"0 0 24 24"}
                fill={"none"}
                stroke={"var(--accent)"}
                strokeWidth={"1.9"}
                strokeLinecap={"round"}
                strokeLinejoin={"round"}
              >
                <rect
                  x={"3"}
                  y={"4"}
                  width={"18"}
                  height={"16"}
                  rx={"2"}
                />
                <path
                  d={"M3 9h18"}
                />
              </svg>
              {"\n        "}
            </span>
            {"\n        "}
            <span
              className={"tb-proj-name"}
              style={{ fontSize: "14px", fontWeight: "600", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}
            >
              {"AI agents for scientific discovery"}
            </span>
            {"\n        "}
            <svg
              width={"13"}
              height={"13"}
              viewBox={"0 0 24 24"}
              fill={"none"}
              stroke={"var(--muted)"}
              strokeWidth={"2"}
              strokeLinecap={"round"}
              strokeLinejoin={"round"}
              style={{ flex: "none" }}
            >
              <path
                d={"M6 9l6 6 6-6"}
              />
            </svg>
            {"\n      "}
          </button>
          {"\n      "}
          <div
            className={"tb-proj-menu"}
            style={{ display: "none", position: "absolute", top: "calc(100% + 6px)", left: "0", zIndex: "70", width: "336px", background: "var(--card)", border: "1px solid var(--border)", borderRadius: "12px", boxShadow: "0 14px 34px rgba(var(--sh),.16)", padding: "5px" }}
          >
            {"\n        "}
            <button
              className={"tb-proj-new dsh-2b56a642"}
              type={"button"}
              style={{ width: "100%", display: "flex", alignItems: "center", gap: "10px", padding: "7px 10px", border: "none", background: "none", borderRadius: "8px", cursor: "pointer", fontFamily: "inherit", textAlign: "left", color: "var(--fg)", transition: "background .14s ease" }}
            >
              {"\n          "}
              <span
                style={{ width: "22px", height: "22px", display: "flex", alignItems: "center", justifyContent: "center", flex: "none" }}
              >
                <svg
                  width={"15"}
                  height={"15"}
                  viewBox={"0 0 24 24"}
                  fill={"none"}
                  stroke={"currentColor"}
                  strokeWidth={"1.9"}
                  strokeLinecap={"round"}
                  strokeLinejoin={"round"}
                  style={{ color: "var(--muted)" }}
                >
                  <path
                    d={"M12 5v14M5 12h14"}
                  />
                </svg>
              </span>
              {"\n          "}
              <span
                style={{ fontSize: "13px", fontWeight: "500" }}
              >
                {"New project"}
              </span>
              {"\n        "}
            </button>
            {"\n        "}
            <div
              style={{ height: "1px", background: "var(--divider)", margin: "4px 5px" }}
            />
            {"\n        "}
            <div
              style={{ padding: "5px 10px 3px", fontSize: "10.5px", fontWeight: "600", letterSpacing: ".07em", textTransform: "uppercase", color: "var(--muted2)" }}
            >
              {"Projects"}
            </div>
            {"\n        "}
            <button
              className={"tb-proj-item dsh-2b56a642"}
              type={"button"}
              data-cur={"1"}
              style={{ width: "100%", display: "flex", alignItems: "center", gap: "10px", padding: "7px 10px", border: "none", background: "none", borderRadius: "8px", cursor: "pointer", fontFamily: "inherit", textAlign: "left", transition: "background .14s ease" }}
            >
              {"\n          "}
              <span
                className={"tb-anch-l"}
                style={{ display: "flex", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none", fontFamily: "'Newsreader',serif", fontSize: "12.5px", fontWeight: "500", color: "var(--fg2)" }}
              >
                {"B"}
              </span>
              {"\n          "}
              <span
                className={"tb-anch-m"}
                style={{ display: "none", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none" }}
              >
                <svg
                  width={"14"}
                  height={"14"}
                  viewBox={"0 0 32 32"}
                  fill={"none"}
                  stroke={"var(--muted)"}
                  strokeWidth={"2.4"}
                  strokeLinejoin={"miter"}
                  strokeLinecap={"butt"}
                >
                  <path
                    d={"M16 4.5 L26 10.5 L26 21.5 L16 27.5 L6 21.5 L6 10.5 Z"}
                  />
                  <path
                    d={"M16 4.5 L16 16 M16 16 L6 21.5 M16 16 L26 21.5"}
                  />
                </svg>
              </span>
              {"\n          "}
              <span
                className={"tb-anch-f"}
                style={{ display: "none", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none" }}
              >
                <svg
                  width={"12"}
                  height={"12"}
                  viewBox={"0 0 24 24"}
                  fill={"none"}
                  stroke={"var(--muted)"}
                  strokeWidth={"1.9"}
                  strokeLinecap={"round"}
                  strokeLinejoin={"round"}
                >
                  <rect
                    x={"3"}
                    y={"4"}
                    width={"18"}
                    height={"16"}
                    rx={"2"}
                  />
                  <path
                    d={"M3 9h18"}
                  />
                </svg>
              </span>
              {"\n          "}
              <span
                style={{ display: "flex", flexDirection: "column", gap: "1.5px", minWidth: "0", flex: "1" }}
              >
                {"\n            "}
                <span
                  className={"tb-proj-nm"}
                  style={{ fontSize: "13px", fontWeight: "500", color: "var(--fg)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}
                >
                  {"AI agents for scientific discovery"}
                </span>
                {"\n            "}
                <span
                  style={{ fontSize: "11.5px", color: "var(--muted)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}
                >
                  {"354 papers\u00a0\u00a08 runs\u00a0\u00a0edited today"}
                </span>
                {"\n          "}
              </span>
              {"\n          "}
              <svg
                className={"tb-proj-check"}
                width={"15"}
                height={"15"}
                viewBox={"0 0 24 24"}
                fill={"none"}
                stroke={"var(--accent)"}
                strokeWidth={"2.2"}
                strokeLinecap={"round"}
                strokeLinejoin={"round"}
                style={{ flex: "none", display: "block" }}
              >
                <path
                  d={"M5 12l5 5 9-10"}
                />
              </svg>
              {"\n        "}
            </button>
            {"\n        "}
            <button
              className={"tb-proj-item dsh-2b56a642"}
              type={"button"}
              data-cur={"0"}
              style={{ width: "100%", display: "flex", alignItems: "center", gap: "10px", padding: "7px 10px", border: "none", background: "none", borderRadius: "8px", cursor: "pointer", fontFamily: "inherit", textAlign: "left", transition: "background .14s ease" }}
            >
              {"\n          "}
              <span
                className={"tb-anch-l"}
                style={{ display: "flex", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none", fontFamily: "'Newsreader',serif", fontSize: "12.5px", fontWeight: "500", color: "var(--fg2)" }}
              >
                {"E"}
              </span>
              {"\n          "}
              <span
                className={"tb-anch-m"}
                style={{ display: "none", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none" }}
              >
                <svg
                  width={"14"}
                  height={"14"}
                  viewBox={"0 0 32 32"}
                  fill={"none"}
                  stroke={"var(--muted)"}
                  strokeWidth={"2.4"}
                  strokeLinejoin={"miter"}
                  strokeLinecap={"butt"}
                >
                  <path
                    d={"M16 4.5 L26 10.5 L26 21.5 L16 27.5 L6 21.5 L6 10.5 Z"}
                  />
                  <path
                    d={"M16 4.5 L16 16 M16 16 L6 21.5 M16 16 L26 21.5"}
                  />
                </svg>
              </span>
              {"\n          "}
              <span
                className={"tb-anch-f"}
                style={{ display: "none", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none" }}
              >
                <svg
                  width={"12"}
                  height={"12"}
                  viewBox={"0 0 24 24"}
                  fill={"none"}
                  stroke={"var(--muted)"}
                  strokeWidth={"1.9"}
                  strokeLinecap={"round"}
                  strokeLinejoin={"round"}
                >
                  <rect
                    x={"3"}
                    y={"4"}
                    width={"18"}
                    height={"16"}
                    rx={"2"}
                  />
                  <path
                    d={"M3 9h18"}
                  />
                </svg>
              </span>
              {"\n          "}
              <span
                style={{ display: "flex", flexDirection: "column", gap: "1.5px", minWidth: "0", flex: "1" }}
              >
                {"\n            "}
                <span
                  className={"tb-proj-nm"}
                  style={{ fontSize: "13px", fontWeight: "500", color: "var(--fg)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}
                >
                  {"Evolutionary multi-objective optimization"}
                </span>
                {"\n            "}
                <span
                  style={{ fontSize: "11.5px", color: "var(--muted)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}
                >
                  {"500 papers\u00a0\u00a03 runs\u00a0\u00a0edited 2d ago"}
                </span>
                {"\n          "}
              </span>
              {"\n          "}
              <svg
                className={"tb-proj-check"}
                width={"15"}
                height={"15"}
                viewBox={"0 0 24 24"}
                fill={"none"}
                stroke={"var(--accent)"}
                strokeWidth={"2.2"}
                strokeLinecap={"round"}
                strokeLinejoin={"round"}
                style={{ flex: "none", display: "none" }}
              >
                <path
                  d={"M5 12l5 5 9-10"}
                />
              </svg>
              {"\n        "}
            </button>
            {"\n        "}
            <button
              className={"tb-proj-item dsh-2b56a642"}
              type={"button"}
              data-cur={"0"}
              style={{ width: "100%", display: "flex", alignItems: "center", gap: "10px", padding: "7px 10px", border: "none", background: "none", borderRadius: "8px", cursor: "pointer", fontFamily: "inherit", textAlign: "left", transition: "background .14s ease" }}
            >
              {"\n          "}
              <span
                className={"tb-anch-l"}
                style={{ display: "flex", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none", fontFamily: "'Newsreader',serif", fontSize: "12.5px", fontWeight: "500", color: "var(--fg2)" }}
              >
                {"H"}
              </span>
              {"\n          "}
              <span
                className={"tb-anch-m"}
                style={{ display: "none", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none" }}
              >
                <svg
                  width={"14"}
                  height={"14"}
                  viewBox={"0 0 32 32"}
                  fill={"none"}
                  stroke={"var(--muted)"}
                  strokeWidth={"2.4"}
                  strokeLinejoin={"miter"}
                  strokeLinecap={"butt"}
                >
                  <path
                    d={"M16 4.5 L26 10.5 L26 21.5 L16 27.5 L6 21.5 L6 10.5 Z"}
                  />
                  <path
                    d={"M16 4.5 L16 16 M16 16 L6 21.5 M16 16 L26 21.5"}
                  />
                </svg>
              </span>
              {"\n          "}
              <span
                className={"tb-anch-f"}
                style={{ display: "none", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none" }}
              >
                <svg
                  width={"12"}
                  height={"12"}
                  viewBox={"0 0 24 24"}
                  fill={"none"}
                  stroke={"var(--muted)"}
                  strokeWidth={"1.9"}
                  strokeLinecap={"round"}
                  strokeLinejoin={"round"}
                >
                  <rect
                    x={"3"}
                    y={"4"}
                    width={"18"}
                    height={"16"}
                    rx={"2"}
                  />
                  <path
                    d={"M3 9h18"}
                  />
                </svg>
              </span>
              {"\n          "}
              <span
                style={{ display: "flex", flexDirection: "column", gap: "1.5px", minWidth: "0", flex: "1" }}
              >
                {"\n            "}
                <span
                  className={"tb-proj-nm"}
                  style={{ fontSize: "13px", fontWeight: "500", color: "var(--fg)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}
                >
                  {"Hyper-parameter optimization"}
                </span>
                {"\n            "}
                <span
                  style={{ fontSize: "11.5px", color: "var(--muted)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}
                >
                  {"2.3k papers\u00a0\u00a011 runs\u00a0\u00a0edited 4d ago"}
                </span>
                {"\n          "}
              </span>
              {"\n          "}
              <svg
                className={"tb-proj-check"}
                width={"15"}
                height={"15"}
                viewBox={"0 0 24 24"}
                fill={"none"}
                stroke={"var(--accent)"}
                strokeWidth={"2.2"}
                strokeLinecap={"round"}
                strokeLinejoin={"round"}
                style={{ flex: "none", display: "none" }}
              >
                <path
                  d={"M5 12l5 5 9-10"}
                />
              </svg>
              {"\n        "}
            </button>
            {"\n        "}
            <button
              className={"tb-proj-item dsh-2b56a642"}
              type={"button"}
              data-cur={"0"}
              style={{ width: "100%", display: "flex", alignItems: "center", gap: "10px", padding: "7px 10px", border: "none", background: "none", borderRadius: "8px", cursor: "pointer", fontFamily: "inherit", textAlign: "left", transition: "background .14s ease" }}
            >
              {"\n          "}
              <span
                className={"tb-anch-l"}
                style={{ display: "flex", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none", fontFamily: "'Newsreader',serif", fontSize: "12.5px", fontWeight: "500", color: "var(--fg2)" }}
              >
                {"C"}
              </span>
              {"\n          "}
              <span
                className={"tb-anch-m"}
                style={{ display: "none", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none" }}
              >
                <svg
                  width={"14"}
                  height={"14"}
                  viewBox={"0 0 32 32"}
                  fill={"none"}
                  stroke={"var(--muted)"}
                  strokeWidth={"2.4"}
                  strokeLinejoin={"miter"}
                  strokeLinecap={"butt"}
                >
                  <path
                    d={"M16 4.5 L26 10.5 L26 21.5 L16 27.5 L6 21.5 L6 10.5 Z"}
                  />
                  <path
                    d={"M16 4.5 L16 16 M16 16 L6 21.5 M16 16 L26 21.5"}
                  />
                </svg>
              </span>
              {"\n          "}
              <span
                className={"tb-anch-f"}
                style={{ display: "none", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none" }}
              >
                <svg
                  width={"12"}
                  height={"12"}
                  viewBox={"0 0 24 24"}
                  fill={"none"}
                  stroke={"var(--muted)"}
                  strokeWidth={"1.9"}
                  strokeLinecap={"round"}
                  strokeLinejoin={"round"}
                >
                  <rect
                    x={"3"}
                    y={"4"}
                    width={"18"}
                    height={"16"}
                    rx={"2"}
                  />
                  <path
                    d={"M3 9h18"}
                  />
                </svg>
              </span>
              {"\n          "}
              <span
                style={{ display: "flex", flexDirection: "column", gap: "1.5px", minWidth: "0", flex: "1" }}
              >
                {"\n            "}
                <span
                  className={"tb-proj-nm"}
                  style={{ fontSize: "13px", fontWeight: "500", color: "var(--fg)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}
                >
                  {"Combinatorial optimization"}
                </span>
                {"\n            "}
                <span
                  style={{ fontSize: "11.5px", color: "var(--muted)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}
                >
                  {"860 papers\u00a0\u00a04 runs\u00a0\u00a0edited last week"}
                </span>
                {"\n          "}
              </span>
              {"\n          "}
              <svg
                className={"tb-proj-check"}
                width={"15"}
                height={"15"}
                viewBox={"0 0 24 24"}
                fill={"none"}
                stroke={"var(--accent)"}
                strokeWidth={"2.2"}
                strokeLinecap={"round"}
                strokeLinejoin={"round"}
                style={{ flex: "none", display: "none" }}
              >
                <path
                  d={"M5 12l5 5 9-10"}
                />
              </svg>
              {"\n        "}
            </button>
            {"\n        "}
            <button
              className={"tb-proj-item dsh-2b56a642"}
              type={"button"}
              data-cur={"0"}
              style={{ width: "100%", display: "flex", alignItems: "center", gap: "10px", padding: "7px 10px", border: "none", background: "none", borderRadius: "8px", cursor: "pointer", fontFamily: "inherit", textAlign: "left", transition: "background .14s ease" }}
            >
              {"\n          "}
              <span
                className={"tb-anch-l"}
                style={{ display: "flex", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none", fontFamily: "'Newsreader',serif", fontSize: "12.5px", fontWeight: "500", color: "var(--fg2)" }}
              >
                {"S"}
              </span>
              {"\n          "}
              <span
                className={"tb-anch-m"}
                style={{ display: "none", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none" }}
              >
                <svg
                  width={"14"}
                  height={"14"}
                  viewBox={"0 0 32 32"}
                  fill={"none"}
                  stroke={"var(--muted)"}
                  strokeWidth={"2.4"}
                  strokeLinejoin={"miter"}
                  strokeLinecap={"butt"}
                >
                  <path
                    d={"M16 4.5 L26 10.5 L26 21.5 L16 27.5 L6 21.5 L6 10.5 Z"}
                  />
                  <path
                    d={"M16 4.5 L16 16 M16 16 L6 21.5 M16 16 L26 21.5"}
                  />
                </svg>
              </span>
              {"\n          "}
              <span
                className={"tb-anch-f"}
                style={{ display: "none", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none" }}
              >
                <svg
                  width={"12"}
                  height={"12"}
                  viewBox={"0 0 24 24"}
                  fill={"none"}
                  stroke={"var(--muted)"}
                  strokeWidth={"1.9"}
                  strokeLinecap={"round"}
                  strokeLinejoin={"round"}
                >
                  <rect
                    x={"3"}
                    y={"4"}
                    width={"18"}
                    height={"16"}
                    rx={"2"}
                  />
                  <path
                    d={"M3 9h18"}
                  />
                </svg>
              </span>
              {"\n          "}
              <span
                style={{ display: "flex", flexDirection: "column", gap: "1.5px", minWidth: "0", flex: "1" }}
              >
                {"\n            "}
                <span
                  className={"tb-proj-nm"}
                  style={{ fontSize: "13px", fontWeight: "500", color: "var(--fg)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}
                >
                  {"Search-based software engineering"}
                </span>
                {"\n            "}
                <span
                  style={{ fontSize: "11.5px", color: "var(--muted)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}
                >
                  {"1.5k papers\u00a0\u00a08 runs\u00a0\u00a0edited 2w ago"}
                </span>
                {"\n          "}
              </span>
              {"\n          "}
              <svg
                className={"tb-proj-check"}
                width={"15"}
                height={"15"}
                viewBox={"0 0 24 24"}
                fill={"none"}
                stroke={"var(--accent)"}
                strokeWidth={"2.2"}
                strokeLinecap={"round"}
                strokeLinejoin={"round"}
                style={{ flex: "none", display: "none" }}
              >
                <path
                  d={"M5 12l5 5 9-10"}
                />
              </svg>
              {"\n        "}
            </button>
            {"\n        "}
            <button
              className={"tb-proj-item dsh-2b56a642"}
              type={"button"}
              data-cur={"0"}
              style={{ width: "100%", display: "flex", alignItems: "center", gap: "10px", padding: "7px 10px", border: "none", background: "none", borderRadius: "8px", cursor: "pointer", fontFamily: "inherit", textAlign: "left", transition: "background .14s ease" }}
            >
              {"\n          "}
              <span
                className={"tb-anch-l"}
                style={{ display: "flex", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none", fontFamily: "'Newsreader',serif", fontSize: "12.5px", fontWeight: "500", color: "var(--fg2)" }}
              >
                {"M"}
              </span>
              {"\n          "}
              <span
                className={"tb-anch-m"}
                style={{ display: "none", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none" }}
              >
                <svg
                  width={"14"}
                  height={"14"}
                  viewBox={"0 0 32 32"}
                  fill={"none"}
                  stroke={"var(--muted)"}
                  strokeWidth={"2.4"}
                  strokeLinejoin={"miter"}
                  strokeLinecap={"butt"}
                >
                  <path
                    d={"M16 4.5 L26 10.5 L26 21.5 L16 27.5 L6 21.5 L6 10.5 Z"}
                  />
                  <path
                    d={"M16 4.5 L16 16 M16 16 L6 21.5 M16 16 L26 21.5"}
                  />
                </svg>
              </span>
              {"\n          "}
              <span
                className={"tb-anch-f"}
                style={{ display: "none", width: "22px", height: "22px", borderRadius: "6px", background: "var(--icon-bg)", border: "1px solid var(--border)", alignItems: "center", justifyContent: "center", flex: "none" }}
              >
                <svg
                  width={"12"}
                  height={"12"}
                  viewBox={"0 0 24 24"}
                  fill={"none"}
                  stroke={"var(--muted)"}
                  strokeWidth={"1.9"}
                  strokeLinecap={"round"}
                  strokeLinejoin={"round"}
                >
                  <rect
                    x={"3"}
                    y={"4"}
                    width={"18"}
                    height={"16"}
                    rx={"2"}
                  />
                  <path
                    d={"M3 9h18"}
                  />
                </svg>
              </span>
              {"\n          "}
              <span
                style={{ display: "flex", flexDirection: "column", gap: "1.5px", minWidth: "0", flex: "1" }}
              >
                {"\n            "}
                <span
                  className={"tb-proj-nm"}
                  style={{ fontSize: "13px", fontWeight: "500", color: "var(--fg)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}
                >
                  {"Meta science"}
                </span>
                {"\n            "}
                <span
                  style={{ fontSize: "11.5px", color: "var(--muted)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}
                >
                  {"340 papers\u00a0\u00a02 runs\u00a0\u00a0edited 3w ago"}
                </span>
                {"\n          "}
              </span>
              {"\n          "}
              <svg
                className={"tb-proj-check"}
                width={"15"}
                height={"15"}
                viewBox={"0 0 24 24"}
                fill={"none"}
                stroke={"var(--accent)"}
                strokeWidth={"2.2"}
                strokeLinecap={"round"}
                strokeLinejoin={"round"}
                style={{ flex: "none", display: "none" }}
              >
                <path
                  d={"M5 12l5 5 9-10"}
                />
              </svg>
              {"\n        "}
            </button>
            {"\n        "}
            <div
              style={{ height: "1px", background: "var(--divider)", margin: "4px 5px" }}
            />
            {"\n        "}
            <button
              className={"tb-proj-all dsh-2b56a642"}
              type={"button"}
              style={{ width: "100%", display: "flex", alignItems: "center", gap: "10px", padding: "7px 10px", border: "none", background: "none", borderRadius: "8px", cursor: "pointer", fontFamily: "inherit", textAlign: "left", color: "var(--fg)", transition: "background .14s ease" }}
            >
              {"\n          "}
              <span
                style={{ width: "22px", height: "22px", display: "flex", alignItems: "center", justifyContent: "center", flex: "none" }}
              >
                <svg
                  width={"14"}
                  height={"14"}
                  viewBox={"0 0 24 24"}
                  fill={"none"}
                  stroke={"currentColor"}
                  strokeWidth={"1.8"}
                  strokeLinecap={"round"}
                  strokeLinejoin={"round"}
                  style={{ color: "var(--muted)" }}
                >
                  <rect
                    x={"3"}
                    y={"3"}
                    width={"7"}
                    height={"7"}
                    rx={"1.5"}
                  />
                  <rect
                    x={"14"}
                    y={"3"}
                    width={"7"}
                    height={"7"}
                    rx={"1.5"}
                  />
                  <rect
                    x={"3"}
                    y={"14"}
                    width={"7"}
                    height={"7"}
                    rx={"1.5"}
                  />
                  <rect
                    x={"14"}
                    y={"14"}
                    width={"7"}
                    height={"7"}
                    rx={"1.5"}
                  />
                </svg>
              </span>
              {"\n          "}
              <span
                style={{ fontSize: "13px", fontWeight: "500" }}
              >
                {"All projects"}
              </span>
              {"\n          "}
              <span
                style={{ marginLeft: "auto", fontSize: "11.5px", color: "var(--muted2)" }}
              >
                {"6"}
              </span>
              {"\n        "}
            </button>
            {"\n      "}
          </div>
          {"\n      "}
        </div>
        {"\n    "}
      </div>
      {"\n\n    "}
      <nav
        className={"tb-nav"}
        style={{ flex: "none" }}
      >
        {"\n      "}
        <button
          className={"tb-tab"}
          data-active={"1"}
        >
          {"Build"}
        </button>
        {"\n      "}
        <button
          className={"tb-tab"}
          style={{ position: "relative" }}
        >
          {"Runs"}
          <span
            className={"tb-runs-dot"}
            style={{ display: "none", position: "absolute", top: "5px", right: "5px", width: "6px", height: "6px", borderRadius: "50%", background: "var(--success)" }}
          />
        </button>
        {"\n      "}
        <button
          className={"tb-tab"}
        >
          {"Explore"}
        </button>
        {"\n    "}
      </nav>
      {"\n\n    "}
      <div
        style={{ flex: "1", minWidth: "0", display: "flex", alignItems: "center", justifyContent: "flex-end", gap: "8px" }}
      >
        {"\n      "}
        <div
          className={"tb-dl-wrap"}
          style={{ position: "relative" }}
        >
          {"\n        "}
          <button
            className={"tb-download dsh-2b56a642"}
            aria-haspopup={"true"}
            style={{ display: "flex", alignItems: "center", gap: "7px", padding: "8px 14px", border: "1px solid var(--border)", borderRadius: "9px", background: "var(--card)", color: "var(--fg)", fontFamily: "inherit", fontSize: "13px", fontWeight: "600", cursor: "pointer" }}
          >
            {"\n          "}
            <svg
              width={"15"}
              height={"15"}
              viewBox={"0 0 24 24"}
              fill={"none"}
              stroke={"currentColor"}
              strokeWidth={"1.9"}
              strokeLinecap={"round"}
              strokeLinejoin={"round"}
            >
              <path
                d={"M12 3v12"}
              />
              <path
                d={"M7 11l5 5 5-5"}
              />
              <path
                d={"M4 20h16"}
              />
            </svg>
            {"\n          Download\n        "}
          </button>
          {"\n        "}
          <div
            className={"tb-dl-menu"}
            style={{ display: "none", position: "absolute", top: "calc(100% + 6px)", right: "0", zIndex: "70", width: "268px", background: "var(--card)", border: "1px solid var(--border)", borderRadius: "12px", boxShadow: "0 14px 34px rgba(var(--sh),.16)", padding: "5px" }}
          >
            {"\n          "}
            <div
              className={"tb-dl-head"}
              style={{ display: "flex", alignItems: "baseline", gap: "7px", padding: "6px 10px 5px" }}
            >
              {"\n            "}
              <span
                style={{ fontSize: "10.5px", fontWeight: "600", letterSpacing: ".07em", textTransform: "uppercase", color: "var(--muted2)" }}
              >
                {"Download"}
              </span>
              {"\n            "}
              <span
                className={"tb-dl-sep"}
                style={{ color: "var(--dot-sep)", fontSize: "10.5px" }}
              />
              {"\n            "}
              <span
                className={"tb-dl-run"}
                style={{ fontSize: "11px", fontWeight: "600", color: "var(--fg2)" }}
              >
                {"Run 6"}
              </span>
              {"\n            "}
              <span
                className={"tb-dl-date"}
                style={{ marginLeft: "auto", fontSize: "11px", color: "var(--muted2)" }}
              >
                {"yesterday"}
              </span>
              {"\n          "}
            </div>
            {"\n          "}
            <button
              className={"tb-dl-item dsh-2b56a642"}
              type={"button"}
              data-dl={"csv"}
              style={{ width: "100%", display: "flex", alignItems: "flex-start", gap: "10px", padding: "8px 10px", border: "none", background: "none", borderRadius: "8px", cursor: "pointer", fontFamily: "inherit", textAlign: "left", transition: "background .14s ease" }}
            >
              {"\n            "}
              <svg
                width={"15"}
                height={"15"}
                viewBox={"0 0 24 24"}
                fill={"none"}
                stroke={"currentColor"}
                strokeWidth={"1.8"}
                strokeLinecap={"round"}
                strokeLinejoin={"round"}
                style={{ flex: "none", marginTop: "1.5px", color: "var(--muted)" }}
              >
                <path
                  d={"M14 3v4a1 1 0 0 0 1 1h4"}
                />
                <path
                  d={"M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z"}
                />
                <path
                  d={"M9 13h6M9 17h4"}
                />
              </svg>
              {"\n            "}
              <span
                style={{ display: "flex", flexDirection: "column", gap: "2px", minWidth: "0" }}
              >
                {"\n              "}
                <span
                  style={{ fontSize: "13px", fontWeight: "500", color: "var(--fg)" }}
                >
                  {"Accepted papers"}
                </span>
                {"\n              "}
                <span
                  className={"tb-dl-sub"}
                  style={{ fontSize: "11.5px", color: "var(--muted)" }}
                >
                  {"CSV\u00a0\u00a0"}
                  <span
                    className={"tb-dl-n"}
                  >
                    {"214"}
                  </span>
                  {" papers"}
                </span>
                {"\n            "}
              </span>
              {"\n          "}
            </button>
            {"\n          "}
            <button
              className={"tb-dl-item dsh-2b56a642"}
              type={"button"}
              data-dl={"bundle"}
              style={{ width: "100%", display: "flex", alignItems: "flex-start", gap: "10px", padding: "8px 10px", border: "none", background: "none", borderRadius: "8px", cursor: "pointer", fontFamily: "inherit", textAlign: "left", transition: "background .14s ease" }}
            >
              {"\n            "}
              <svg
                width={"15"}
                height={"15"}
                viewBox={"0 0 24 24"}
                fill={"none"}
                stroke={"currentColor"}
                strokeWidth={"1.8"}
                strokeLinecap={"round"}
                strokeLinejoin={"round"}
                style={{ flex: "none", marginTop: "1.5px", color: "var(--muted)" }}
              >
                <rect
                  x={"3"}
                  y={"4"}
                  width={"18"}
                  height={"4"}
                  rx={"1"}
                />
                <path
                  d={"M5 8v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8"}
                />
                <path
                  d={"M10 12h4"}
                />
              </svg>
              {"\n            "}
              <span
                style={{ display: "flex", flexDirection: "column", gap: "2px", minWidth: "0" }}
              >
                {"\n              "}
                <span
                  style={{ fontSize: "13px", fontWeight: "500", color: "var(--fg)" }}
                >
                  {"Full bundle"}
                </span>
                {"\n              "}
                <span
                  className={"tb-dl-sub"}
                  style={{ fontSize: "11.5px", color: "var(--muted)" }}
                >
                  {"CSVs\u00a0\u00a0BibTeX\u00a0\u00a0graph\u00a0\u00a0stats"}
                </span>
                {"\n            "}
              </span>
              {"\n          "}
            </button>
            {"\n          "}
            <div
              className={"tb-dl-none"}
              style={{ display: "none", flexDirection: "column", gap: "3px", padding: "8px 10px 9px" }}
            >
              {"\n            "}
              <span
                style={{ fontSize: "13px", fontWeight: "500", color: "var(--fg)" }}
              >
                {"No runs yet"}
              </span>
              {"\n            "}
              <span
                style={{ fontSize: "11.5px", color: "var(--muted)", lineHeight: "1.45" }}
              >
                {"Results download per run. Start one with Run pipeline."}
              </span>
              {"\n          "}
            </div>
            {"\n        "}
          </div>
          {"\n      "}
        </div>
        {"\n      "}
        <button
          className={"tb-run dsh-1c12969d"}
          style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: "7px", minWidth: "138px", padding: "8px 16px", border: "none", borderRadius: "9px", background: "var(--primary)", color: "var(--primary-fg)", fontFamily: "inherit", fontSize: "13px", fontWeight: "600", cursor: "pointer" }}
        >
          {"\n        "}
          <svg
            width={"13"}
            height={"13"}
            viewBox={"0 0 24 24"}
            fill={"currentColor"}
            stroke={"none"}
          >
            <path
              d={"M8 5v14l11-7z"}
            />
          </svg>
          {"\n        Run pipeline\n      "}
        </button>
        {"\n      "}
        <button
          className={"pc-theme-toggle dsh-2b56a642"}
          aria-label={"Toggle color theme"}
          style={{ width: "36px", height: "36px", flex: "none", display: "flex", alignItems: "center", justifyContent: "center", border: "1px solid var(--border)", background: "var(--card)", borderRadius: "9px", color: "var(--fg2)", cursor: "pointer" }}
        >
          {"\n        "}
          <svg
            className={"tt-moon"}
            width={"16"}
            height={"16"}
            viewBox={"0 0 24 24"}
            fill={"none"}
            stroke={"currentColor"}
            strokeWidth={"2"}
            strokeLinecap={"round"}
            strokeLinejoin={"round"}
            style={{ display: "block" }}
          >
            <path
              d={"M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8z"}
            />
          </svg>
          {"\n        "}
          <svg
            className={"tt-sun"}
            width={"16"}
            height={"16"}
            viewBox={"0 0 24 24"}
            fill={"none"}
            stroke={"currentColor"}
            strokeWidth={"2"}
            strokeLinecap={"round"}
            strokeLinejoin={"round"}
            style={{ display: "none" }}
          >
            <circle
              cx={"12"}
              cy={"12"}
              r={"4"}
            />
            <path
              d={"M12 2v2M12 20v2M4 12H2M22 12h-2M5.6 5.6l1.4 1.4M17 17l1.4 1.4M18.4 5.6L17 7M7 17l-1.4 1.4"}
            />
          </svg>
          {"\n        "}
          <span
            className={"tt-label"}
            style={{ display: "none" }}
          />
          {"\n      "}
        </button>
        {"\n      "}
        <div
          className={"tb-user-wrap"}
          style={{ position: "relative" }}
        >
          {"\n        "}
          <button
            className={"tb-user dsh-2b56a642"}
            aria-haspopup={"true"}
            aria-label={"Account"}
            style={{ width: "36px", height: "36px", flex: "none", display: "flex", alignItems: "center", justifyContent: "center", padding: "0", border: "1px solid var(--border)", background: "var(--card)", borderRadius: "9px", cursor: "pointer" }}
          >
            {"\n          "}
            <span
              style={{ width: "24px", height: "24px", borderRadius: "50%", background: "var(--icon-bg)", border: "1px solid var(--border)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "10.5px", fontWeight: "600", letterSpacing: ".05em", color: "var(--fg2)" }}
            >
              {"AL"}
            </span>
            {"\n        "}
          </button>
          {"\n        "}
          <div
            className={"tb-user-menu"}
            style={{ display: "none", position: "absolute", top: "calc(100% + 6px)", right: "0", zIndex: "70", width: "224px", background: "var(--card)", border: "1px solid var(--border)", borderRadius: "12px", boxShadow: "0 14px 34px rgba(var(--sh),.16)", padding: "5px" }}
          >
            {"\n          "}
            <div
              style={{ display: "flex", flexDirection: "column", gap: "2px", padding: "7px 10px 8px" }}
            >
              {"\n            "}
              <span
                style={{ fontSize: "13px", fontWeight: "600", color: "var(--fg)" }}
              >
                {"Ada Lovelace"}
              </span>
              {"\n            "}
              <span
                style={{ fontSize: "11.5px", color: "var(--muted)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}
              >
                {"ada@lovelace.edu"}
              </span>
              {"\n          "}
            </div>
            {"\n          "}
            <div
              style={{ height: "1px", background: "var(--divider)", margin: "0 5px 4px" }}
            />
            {"\n          "}
            <button
              className={"tb-user-settings dsh-2b56a642"}
              type={"button"}
              style={{ width: "100%", display: "flex", alignItems: "center", gap: "9px", padding: "8px 10px", border: "none", background: "none", borderRadius: "8px", fontFamily: "inherit", fontSize: "13px", color: "var(--fg)", cursor: "pointer", textAlign: "left", transition: "background .14s ease" }}
            >
              {"\n            "}
              <svg
                width={"14"}
                height={"14"}
                viewBox={"0 0 24 24"}
                fill={"none"}
                stroke={"currentColor"}
                strokeWidth={"1.8"}
                strokeLinecap={"round"}
                strokeLinejoin={"round"}
                style={{ flex: "none", color: "var(--muted)" }}
              >
                <circle
                  cx={"12"}
                  cy={"12"}
                  r={"3"}
                />
                <path
                  d={"M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"}
                />
              </svg>
              {"\n            Settings\n          "}
            </button>
            {"\n          "}
            <button
              className={"tb-user-logout dsh-2b56a642"}
              type={"button"}
              style={{ width: "100%", display: "flex", alignItems: "center", gap: "9px", padding: "8px 10px", border: "none", background: "none", borderRadius: "8px", fontFamily: "inherit", fontSize: "13px", color: "var(--fg)", cursor: "pointer", textAlign: "left", transition: "background .14s ease" }}
            >
              {"\n            "}
              <svg
                width={"14"}
                height={"14"}
                viewBox={"0 0 24 24"}
                fill={"none"}
                stroke={"currentColor"}
                strokeWidth={"1.8"}
                strokeLinecap={"round"}
                strokeLinejoin={"round"}
                style={{ flex: "none", color: "var(--muted)" }}
              >
                <path
                  d={"M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"}
                />
                <path
                  d={"M16 17l5-5-5-5"}
                />
                <path
                  d={"M21 12H9"}
                />
              </svg>
              {"\n            Log out\n          "}
            </button>
            {"\n        "}
          </div>
          {"\n      "}
        </div>
        {"\n    "}
      </div>
      {"\n\n  "}
    </header>
  );
}
