// "In this corpus" — citing passages for ONE demo paper (mock data).
// SUBJECT is the PAPERS index of "Autonomous chemical research with large language models"
// (Boiko et al., Nature 2023). Every group's `p` is the PAPERS index of a paper that
// really cites it in the RUN-37 graph; the passage text is demo content.
export const SUBJECT = 6;

// s = section label as printed by the source, t = the passage
export const GROUPS = [
  { p: 18, items: [
    { s: 'Introduction', t: '…For example, Geneformer, which was pretrained on 30 million single-cell transcriptomes, aids in disease modeling and has successfully identified therapeutic targets for cardiomyopathy through in silico deletion. Researchers have demonstrated that LLMs such as ChemCrow and Coscientist have the potential to automate chemistry experiments, particularly in directed synthesis and chemical reaction prediction. Other models, including LLM4SD, can directly analyze raw experimental data to perform scientific synthesis, inference, and hypothesis generation, aligning with human expert analysis.…' },
    { s: 'Introduction', t: '…In the drug discovery phase, LLMs may automate chemistry experiments, control robotic systems, and suggest novel molecules through interactive platforms for compound generation and editing. During clinical trials, LLMs may streamline patient matching and trial design by analyzing profiles and requirements, while early research suggests they may predict trial outcomes by analyzing historical data.…' },
    { s: 'Introduction', t: '…This extensive training equips them with capabilities such as reasoning, planning, tool use, information retrieval, and role playing in scientific scenarios. In practice, users interact with these models as conversational assistants to address and solve specific problems.…' },
    { s: 'Drug Discovery', t: '…LLMs are increasingly central to this transformation, serving as intelligent interfaces between human researchers and automated systems. They can generate machine-readable protocols from natural language descriptions, helping bridge the gap between experimental intent and execution. They also support synthesis design by recommending retrosynthetic pathways and predicting reaction outcomes.…' },
    { s: 'Drug Discovery', t: '…An emerging area of AI research involves using LLMs as autonomous agents to create and execute scientific experiments. For example, Coscientist demonstrated how LLMs could use web search engines and vector search to gather synthesis information and generate multi-instrument systems code, successfully performing complex reactions like Suzuki and Sonogashira cross-coupling.…' },
    { s: 'Drug Discovery', t: '…LLMs also contribute to retrosynthetic planning and reaction prediction, which are essential for mapping efficient routes from commercially available precursors to target compounds. Recently, general-purpose LLMs like ChemCrow and Coscientist have advanced this field. ChemCrow integrates a broad array of tools, including SMILES conversion, patent checking, and reaction classification, employing a four-step framework, thinking, acting, providing inputs, and analyzing results, to improve LLM performance, surpassing GPT-4 in synthesis planning tasks.…' },
    { s: 'Drug Discovery', t: '…These models are now used in complex chemistry experiments, demonstrating superior performance over specialized LLMs in tasks like retrosynthetic planning and reaction prediction due to their tool use capabilities, such as reading scientific literature and assisting in molecular synthesis. In real-world settings, general LLMs have shown effectiveness in synthesizing molecules and controlling robotic arms.…' },
    { s: 'Drug Discovery', t: '…Despite these advances, their widespread deployment in industries, such as pharmaceuticals, remains limited, indicating the need for further research and development to fully leverage general LLMs in chemistry experiments.…' },
    { s: 'Future Directions', t: '…At the same time, these systems must blend the complementary strengths of general-purpose and specialized models. General LLMs provide broad world knowledge, conversational interfaces, and chain-of-thought reasoning that help scientists frame hypotheses and interpret results. Specialized LLMs, fine-tuned on curated biochemical corpora, deliver high-fidelity predictions for niche tasks such as binding-mode rationalization, QSAR, or protein-ligand docking.…' }
  ] },
  { p: 36, items: [
    { s: 'Agents For Chemical Innovation', t: '…At the time of writing, the code remains unreleased, but a simple example that calculates the square roots of random numbers has been provided to illustrate their approach. These examples underscore the transformative role of LLMs in enhancing and automating chemical processes, which will likely accelerate chemical discovery.…' },
    { s: 'Agents For Chemical Innovation', t: '…The agents in chemistry, as exemplified by ChemCrow and Coscientist, highlight a significant shift towards automation and enhanced efficiency in molecular discovery and scientific research. These systems demonstrate the potential of integrating LLMs with chemical tools and automation frameworks, achieving impressive accuracy and effectiveness in tasks ranging from routine chemical operations to complex reaction optimizations.…' },
    { s: 'Human–AI Collaboration In Chemical Research', t: '…For instance, tasks such as data analysis, literature review, and elements of experimental design are now being automated. This automation liberates chemists to focus on more innovative and intellectually engaging aspects of their work, and the opportunity is to expand productivity and creativity in their science.…' },
    { s: 'LLM-Based Autonomous Agents In Scientific Research', t: '…Another system called Coscientist exemplifies the integration of semi-autonomous robots in planning, conceiving, and performing chemical reactions with minimal human intervention. At its core, the system features a main module named "PLANNER", which is supported by four submodules.…' },
    { s: 'LLM-Based Autonomous Agents In Scientific Research', t: '…Additionally, Coscientist was also used to optimize reaction conditions. In contrast to Ramos et al., who used LLMs within a Bayesian Optimization (BO) algorithm as a surrogate model, Boiko et al. approached the optimization task as a strategic "game" aimed at maximizing reaction yield by selecting optimal reaction conditions. This demonstrates the ability of GPT-4 to effectively reason about popular chemical reactions, possibly via comprehensive coverage in pretraining.…' },
    { s: 'LLM-Based Autonomous Agents In Scientific Research', t: '…These submodules, or tools, are responsible for performing actions such as searching the web for organic synthesis, executing Python code, searching the hardware documentation, and performing a reaction in an automated lab. Utilizing this framework, the Coscientist successfully conducted two types of chemical coupling reactions, Suzuki–Miyaura and Sonogashira, in a semi-automated fashion, with manual handling of initial reagents and solvents.…' },
    { s: 'Introduction', t: '…Inspired by successes in natural language processing (NLP), LLMs were adapted for chemical language (e.g., Simplified Molecular Input Line Entry System (SMILES)) to tackle tasks from synthesis prediction to molecule generation. We will then explore the integration of LLMs into autonomous agents as illustrated by M. Bran et al. and Boiko et al., which may be used for data interpretation or, for example, to experiment with robotic systems. We are at a crossroads where AI enables chemists to solve major global problems faster and streamline routine lab tasks.…' },
    { s: 'Agents For Experiments Planning', t: '…The Large Language Models-based Reaction Development Framework (LLM-RDF) automates every step of the synthesis workflow. While other studies focus on the literature review, HTS, and reaction optimization, LLM-RDF can support researchers from literature search until the product purification. Using this system, the authors showed they could design a copper/TEMPO catalyzed alcohol oxidation reaction, optimize reaction conditions, engineer a scale-up, and purify the products, obtaining a yield of 86% and a purity >98% while producing 1 gram of product.…' }
  ] },
  { p: 31, items: [
    { s: 'Agent-Based Architecture In Self-Driving Laboratories', t: '…This evolution is particularly rapid in chemistry. Systems such as ChemCrow and Coscientist demonstrated that LLM agents could autonomously plan synthesis routes by querying databases like PubChem and executing code scripts. However, while these software agents demonstrated impressive reasoning capabilities, they remain largely disembodied, capable of planning experiments but still reliant on humans for physical execution.…' },
    { s: 'Agent-Based Architecture In Self-Driving Laboratories', t: '…The workflow is organized into five functional components: Comprehension, Design, Execution, Analysis, and Optimization, which, respectively, support literature/knowledge grounding, experiment and computation planning, robotic and instrument control with real-time logging, data processing and pattern recognition, and active-learning/Bayesian (including multi-objective) optimization. For each component, representative LLM-agent systems are listed, highlighting how specialized agents can be composed into a coordinated pipeline.…' },
    { s: 'Agent-Based Architecture In Self-Driving Laboratories', t: '…It must also handle scheduling, interlocking, and exceptions during execution. Systems such as Coscientist and ChemAgents demonstrate feasible pathways for autonomously executing complex physical tasks by enabling agents to read hardware documentation, invoke hierarchical subagents, or adopt structured action representations.…' },
    { s: 'Evolution Of End-To-End Chemical Research Agents', t: '…Coscientist first bridged the gap between Design and Execution, validating the feasibility of agent-driven hardware. ChemCrow subsequently strengthened Comprehension and Design, introducing tool-augmented rigor to mitigate hallucinations. Finally, LLM-RDF integrated a distinct Analysis module via multiagent collaboration, closing the loop from experimental data back to hypothesis generation.…' },
    { s: 'Evolution Of End-To-End Chemical Research Agents', t: '…a. System\u2019s architecture of Coscientist. Reproduced from ref, Copyright 2023, Springer Nature. b. Overview and expert-designed toolset of ChemCrow.…' }
  ] },
  { p: 40, items: [
    { s: 'Laboratory Automation', t: '…Just as they could be used for benign purposes like synthesizing DEET, they could be used to harmful ends. Boiko et al. found that LLMs such as GPT-4 could be directed to synthesize compounds that are dangerous or illegal if given an appropriate prompt, bypassing the model\u2019s "guard rails". While this does not introduce a new capability for experienced chemical practitioners…' },
    { s: 'Laboratory Automation', t: '…As Boiko et al. and Bran et al. have shown, LLMs can perform chemical procedures entirely without human intervention. But since these models lack agency, they cannot undergo safety training, receive certifications, or be held accountable for unsafe behavior.…' },
    { s: 'Introduction', t: '…The chemical sciences have not been immune to the proliferation of foundation models. There have been a number of recent efforts seeking to evaluate the capabilities of generative models like LLMs for chemical tasks, from answering simple questions and mining text to performing complex experiments by interfacing with laboratory hardware. Efforts to create chemistry-specific foundation models have also appeared, including protein-folding models and "universal" ML interatomic potentials (MLIPs).…' },
    { s: 'Laboratory Automation', t: '…Thus far, this approach has been demonstrated on well-studied systems. Boiko et al. applied their LLM-based laboratory automation system, Coscientist, to optimize Suzuki and Sonogashira cross-coupling reactions, while Bran et al.\u2019s ChemCrow demonstrated the ability to synthesize non-trivial products such as N,N-diethyl-meta-toluamide (DEET). In the area of optimization, LLM-based approaches appear to be competitive with the more traditional Bayesian optimization. It is unclear how models like ChemCrow and Coscientist will be able to generate and execute experimental plans to study truly novel chemical or materials systems for which no literature recipes exist.…' }
  ] },
  { p: 39, items: [
    { s: 'The Role Of LLMs And Advanced Reasoning', t: '…While mostly limited to domain-specific tasks and relatively narrow use-cases, transfer learning approaches and advances in agentic AI systems have begun to unlock the potential of multisystem control and integration along the drug discovery pipeline. But, agentic AI has so far only achieved the lowest level of advanced reasoning-based autonomous planning and execution of biomedical research, limited to pre-defined tasks and methodologies.…' },
    { s: 'The Role Of LLMs And Advanced Reasoning', t: '…Notably, ChemCrow and Coscientist, LLM-based platforms with Retrieval-Augmented Generation (RAG)-like abilities to utilize external tools for subtasks such as literature search, molecular property analysis and prediction, synthesis planning, and safety assessment, can take a plain-language prompt, such as "Plan and execute the synthesis of an insect repellent," and synthesize an appropriate compound using laboratory equipment.…' },
    { s: 'The Role Of LLMs And Advanced Reasoning', t: '…Another persistent issue is agent coordination, enabling multiple specialized agents (e.g., for chemistry, biology, and clinical trial design) to collaborate without task overlap, error propagation, or context loss. While frameworks like ChemCrow and Coscientist demonstrate tool-use capabilities, they are often brittle when agents must hand off partial results or dynamically adjust plans, underscoring the need for robust central orchestrators and agent communication protocols, which remain underdeveloped in most current implementations.…' },
    { s: 'A Vision For AI-Orchestrated Drug Discovery', t: '…Biology agents operate automated laboratories, nominating disease-associated targets from compiling published data sources and in vitro experimental validation models. These discovery-based modules scan the literature, devise hypotheses and experimental plans, and validate as necessary with in vitro experimentation, as shown in early prototypes of controllers like DORA and Coscientist, or in more specialized laboratory experiment planners like CRISPR-GPT.…' }
  ] },
  { p: 48, items: [
    { s: 'Introduction', t: '…Over the last year, a surge of excitement has arisen around the potentially transformative role of machine learning (ML) or artificial intelligence in many areas of technology, science, and society. This has been driven by the remarkable performance of large language models (LLMs) and image generation diffusion models.…' },
    { s: 'Introduction', t: '…Given the excitement around these technologies, there is a natural tendency to either assume they will profoundly transform every field or dismiss them as "overhyped".…' },
    { s: 'Robotics And Self-Driving Laboratories', t: '…Recent articles provide a detailed demonstration of the potential of LLMs in chemistry more generally. LLMs will become increasingly integral to scientific meetings and conferences, offering real-time notes, suggestions, and relevant literature based on the extensive training data encoded in their weights. They will play a crucial role in reviewing and improving the scientific literature, making research more accessible and efficient.…' },
    { s: 'Large Language Models', t: '…Their utility is expected to increase as they become more accurate and less prone to producing erroneous outputs ("hallucinations"). Recent articles provide a detailed demonstration of the potential of LLMs in chemistry more generally.…' }
  ] },
  { p: 20, items: [
    { s: null, t: '…Artificial intelligence (AI) is reshaping scientific research and laboratory automation. Large language models (LLMs) can perform aspects of scientific reasoning, which could in principle reduce human decision-making as a rate-limiting step in closed-loop automated experiments. Yet the reasoning performance of LLMs compared with human experts in complex, noisy, long-running laboratory experiments is largely unexplored.…' },
    { s: 'Main', t: '…This has led to methods such as Bayesian optimisation for automating experimental decision making. Recently, there has been much interest in large language models (LLMs) and agentic frameworks to guide closed-loop chemistry experiments due to their inherent capacity to inject chemical context into high-dimensional, non-convex exploration spaces. Previously, a benchmarking study across 2,700 question and answer pairs suggested that LLMs could outperform human chemists for such knowledge tasks, albeit with limitations.…' },
    { s: 'Main', t: '…However, as also noted by others, the real-time decision-making performance of LLMs over long-horizon closed-loop chemistry laboratory experiments is sparsely explored.…' },
    { s: 'Comparison Of Performance And Strategy', t: '…Best H2 evolution rate found in run. Number of exact repeats targeted for best formulation in human and LLM runs in Phase 3. Mean H2 evolution rate for best formulation found, averaged over the number of exact repeats of that formulation in the run.…' }
  ] },
  { p: 49, items: [
    { s: 'Methods', t: '…We examined four different strategies: (i) random sampling, representing traditional trial-and-error; (ii) LLM-driven prediction, which mimics the decision-making process by a human chemist and leverages chemical intuition without statistical learning; (iii) ML-based optimization, which applies a purely statistical approach and uses Bayesian optimization (BO) for parameter selection, with code generated by LLMs that utilize expected improvement on a Gaussian process; and (iv) a hybrid LLM–ML approach, where LLMs guide the initial parameter selection.…' },
    { s: 'Benchmarking LLMs Auto Code Generation', t: '…Finally, in task 4, LLMs were tasked with generating executable scripts for liquid handling robots based on the suggestion made by Task 2 or Task 3. This task demonstrated the practical applicability of LLM-generated code in automating physical processes in the lab, consistent with the previous literature findings, with successful execution reflecting the LLMs\u2019 capacity to integrate digital and physical workflows effectively.…' },
    { s: 'Introduction', t: '…Simultaneously, large language models (LLMs) have gained attention in chemical research, helping researchers streamline and enhance their digital workflows through intuitive natural language prompts. In essence, ML provides a toolbox for specific tasks in chemical research and LLMs serve as meta-tools that enhance the accessibility of these computational tools, bridging the gap between digital proficiency and chemical expertise.…' }
  ] },
  { p: 34, items: [
    { s: 'Results', t: '…We used a batch approach on the screening electrochemical reactor with each batch comprising 3 to 5 reactions, analyzed and adjusted based on the NMR yield outcomes to guide subsequent experimental conditions. We developed and examined four different strategies: random sampling, LLM-driven prediction, ML-based optimization, and a hybrid LLM–ML approach, where LLMs guide the initial parameter selection.…' },
    { s: 'Introduction', t: '…In essence, ML provides a toolbox for specific tasks in chemical research and LLMs serve as meta-tools that enhance the accessibility of these computational tools, bridging the gap between digital proficiency and chemical expertise. Consequently, the integration between the mathematical rigor of ML and the language understanding and domain-specific knowledge of LLMs can make data-driven methodologies accessible to a broader community of chemists.…' },
    { s: 'Methods', t: '…This task demonstrated the practical applicability of LLM-generated code in automating physical processes in the lab, consistent with the previous literature findings, with successful execution reflecting the LLMs\u2019 capacity to integrate digital and physical workflows effectively. Interestingly, models such as o1 and o1-mini spent more time and tokens on reasoning before responding and code writing, and such behavior leads to better performance in both code executability and correctness.…' },
    { s: 'Introduction', t: '…ML-driven automation platforms typically consist of four major stages: data collection and preprocessing, model development and training, automation system design, and validation of model predictions. These platforms have demonstrated substantial potential in drug discovery, material development, chemical synthesis, and real-time characterization, providing a strong foundation for the advancement of intelligent synthesis technologies.…' },
    { s: 'Coscientist AI System', t: '…The team at Carnegie Mellon University developed an AI system named Coscientist by integrating the Transformer-based large language model GPT-4 with laboratory automation technology. This system can autonomously design and execute the synthesis of known compounds, including drugs such as acetaminophen and aspirin. In the Coscientist architecture, users simply input text instructions to assign tasks.…' },
    { s: 'Introduction', t: '…A typical example among them is the work published by Zheng et al., who utilized this workflow for promoting reticular chemistry discovery. Furthermore, retrieval-augmented generation (RAG) coupled with LLM exhibited encouraging potential to provide desired function. By conditioning generation on curated sources at query time, RAG enables dynamic extraction of reaction schemes while preserving stoichiometry and other hard constraints.…' },
    { s: 'Future Perspectives', t: '…A typical example reported by Boiko et al. has demonstrated LLM\u2019s advanced capabilities for (semi-)autonomous experimental design and execution. In the future, Synthesis-GPT has the potential to integrate with laboratory hardware systems and develop into a smart center that connects computational design with real-world experiments.…' }
  ] },
  { p: 35, items: [
    { s: 'Boiko Et Al Developed A GPT-4 Motivated System', t: '…Coscientist. As illustrated in Figure 8a, this system integrates multiple functional modules including Planner, Web searcher, Code execution, Docs searcher, and Automation.…' },
    { s: 'Boiko Et Al Developed A GPT-4 Motivated System', t: '…PDDLStream subsequently generates a sequence of actions for the robot execution. Reproduced with permission, 2023, Nature.…' },
    { s: null, t: '…Autonomous material experiment platform empowered by LMs. (a) The architecture of "Coscientist". Coscientist integrates multiple message-exchanging modules.…' },
    { s: 'Introduction', t: '…Recent advances in transformer-based large language models (LLMs) have created new opportunities for materials\u2019 informatics research. Models like generative pretrained transformer (GPT), bidirectional encoder representations from transformers (BERT), and Qwen demonstrate remarkable capabilities in processing unstructured technical text while maintaining contextual understanding. In materials chemistry, LLMs are already being used to extract and generate chemical knowledge.…' },
    { s: 'Introduction', t: '…For instance, Zheng et al. used prompt-engineered ChatGPT to mine synthesis parameters of metal-organic frameworks (MOFs) from literature, producing structured data. Similarly, Boiko et al. developed Coscientist, an autonomous lab assistant driven by GPT-4, which can plan and execute complex organic synthesis experiments with minimal human intervention.…' },
    { s: 'Introduction', t: '…Although effective, they tend to overlook a rich yet underutilized source of knowledge embedded in unstructured textual data, namely scientific literature. Accumulated over decades, these texts contain nuanced insights into material behaviors, synthesis methods, and performance characteristics that are difficult to quantify and are rarely captured in conventional numerical databases.…' },
    { s: 'Introduction', t: '…To bridge this gap, natural language processing (NLP) models have been employed to extract and encode semantic information from scientific texts. Models like Skip-gram and large language models (LLMs) compress textual data into numerical vector embeddings, capturing contextual meanings (e.g., the concept of "Alloys") for use in downstream machine learning tasks.…' }
  ] },
  { p: 37, items: [
    { s: 'Introduction', t: '…Prior works have limitations in scalability, which constrain their ability to manage complex tool sets and finish tasks that require many steps. These systems typically construct a single prompt that embeds both task instructions and the entire tool set.…' },
    { s: 'Introduction', t: '…To address some of these issues, works such as Boiko et al. introduce modular architectures that allow the developer to manually divide tools into components. Additionally, they rely on RAG for data access, which often screens and retrieves documents based on relevance rather than a deeper understanding of their structure.…' },
    { s: 'Introduction', t: '…Despite challenges, pioneering efforts to develop automated LLM-based agents to carry out experiments are already underway. For example, in Boiko et al. and Bran et al., researchers equipped LLM-based agents with tools that allowed them to acquire professional knowledge from the expert-designed tool kit and even the internet. These agents were then capable of performing chemistry experiments on the basis of this knowledge.…' }
  ] },
  { p: 32, items: [
    { s: 'Simplified Adoption Through A Natural Language Interface', t: '…Analogous methods have recently proven to be powerful enabling technologies for automated or self-driving laboratories. For instance, ChemCrow, reported by Schwaller, White and co-workers, uses iterative large language model (LLM) prompting and tool integration to propose synthetic routes for organic molecules. Coscientist, recently described by Boiko et al., uses a related approach and adds the ability to generate instrument operation code for automated systems.…' },
    { s: 'Simplified Adoption Through A Natural Language Interface', t: '…Coscientist, recently described by Boiko et al., uses a related approach and adds the ability to generate instrument operation code for automated systems. Notably, Chemspyd could readily be integrated into these types of systems.…' },
    { s: 'Simplified Adoption Through A Natural Language Interface', t: '…In our implementation, all Chemspyd functions, along with their natural language documentation and all parameters, are organized in an associative array. We use a similar approach as Boiko et al., demonstrating that it generalizes well to a domain-specific language unknown to GPT-4. Incoming natural language instructions are segmented into structured commands, which are then matched to the classes and functions in the associative array based on cosine similarity.…' },
    { s: 'Introduction', t: '…Some LLMs are specifically trained to address domain-specific knowledge and technical complexities, enhancing their utility in relevant applications. For example, Boiko et al. introduced a LLM-driven agent that autonomously designs, plans and executes experiments by using web search, documentation and robot APIs. In addition, Bran et al. used GPT-4 augmented with 18 chemistry tools to plan and execute syntheses on a cloud-connected robotic platform.…' },
    { s: 'Discussion', t: '…Furthermore, the integration of automation technologies with powerful LLMs will open the door to developing a sought-after system that autonomously designs and executes scientific experiments. We anticipate that this work will inspire further research into the application of language technologies across a broader range of microfluidic applications.…' },
    { s: 'Introduction', t: '…LLMs have demonstrated broad applicability across various disciplines, with notable contributions in specialised areas such as chemistry, biology, biomedical research, materials science, and medicine, offering significant benefits in automating and enhancing research processes. Furthermore, LLMs have played a pivotal role in advancing scientific discovery and fostering technological innovation.…' },
    { s: 'Discussion', t: '…While effective within their defined parameters, these frameworks do not incorporate LLMs or comparable LLM agents, making it challenging to integrate digital discovery platforms at the state of the art. However, our work is capable of transforming them into closed-loop digital discovery platforms that encompass literature synthesis, hypothesis generation, autonomous design, execution in self-driving laboratories, analysis of results, and the generation of new hypotheses.…' }
  ] },
  { p: 9, items: [
    { s: 'Introduction', t: '…These systems can be turned into task-oriented autonomous agents by allowing them to iteratively propose and execute solutions.…' },
    { s: 'Discussion', t: '…Research into LLM-based AI agents is ongoing, with several prototypes having been demonstrated. Although the optimal architecture remains an open question, current demos typically add several elements to the base LLM, such as: providing the LLM with access to various tools (software, web browsing, etc.), the ability to store information about its ongoing work…' },
    { s: 'Discussion', t: '…RAG LLMs have been used to build domain-specific chatbots for science, and to provide an interface to vast materials data that can be distilled as requested by the user. More generally, the AI model can be exploited as a co-pilot to help the user access specialized knowledge or tools, as has been demonstrated for catalyst research, chemistry experiments, and chemistry tools. A valid concern is that the reasoning of LLMs, being well below human scientists, would be insufficient to be useful.…' }
  ] },
  { p: 43, items: [
    { s: 'Discussion', t: '…Unfortunately, the latter do not provide the ease of access and usability that GPT models do. Consequently, we expect that LLMs will increasingly be employed in human interaction settings, facilitating the integration of various chemical tools through natural language interfaces as is being pioneered by Bran and Boiko et al. Finally, we could demonstrate in the present study that classical machine learning techniques can achieve state-of-the-art performance in the prediction of antimicrobial activity and hemolysis.…' },
    { s: 'Discussion', t: '…This finding is especially interesting, as it showcases that good performance can be achieved by less complex models, putting the emphasis on data quality rather than model complexity.…' },
    { s: 'Introduction', t: '…Hereby, the models mainly orchestrate a set of tools to solve chemistry tasks starting from a natural language prompt. However, to the best of our knowledge LLMs have not been implemented to predict the bioactivity of peptides yet.…' }
  ] },
  { p: 47, items: [
    { s: 'Recent Advances In AI For SDLs', t: '…Within the SDL paradigm, their role is rapidly expanding beyond knowledge retrieval to that of central agents of scientific discovery. Unlike traditional approaches, where years of coding expertise or specialized software training were prerequisites, LLMs provide a universal natural language interface that enables direct interaction with experimental and computational systems. This capacity lowers the barrier to entry, fosters interdisciplinary collaboration, and allows even non-experts to leverage SDL infrastructures.…' },
    { s: 'Recent Advances In AI For SDLs', t: '…Beyond direct extraction, LLMs now complement missing knowledge through retrieval-augmented generation (RAG), which grounds responses in external sources such as Wikipedia, Google Scholar, and arXiv and domain-specific databases. Systems such as ChemCrow and Coscientist exemplify this approach, combining literature extraction with web-based retrieval to extend capabilities from knowledge mining to experimental design and execution.…' },
    { s: 'Recent Advances In AI For SDLs', t: '…Their utility extends beyond knowledge mining to include the control of experimental equipment and the interpretation of results within SDL environments. Traditionally, researchers have interacted with instruments through direct programming or specialized interfaces, but LLMs can now translate natural language instructions into executable control commands, greatly improving accessibility to complex automation infrastructures.…' },
    { s: 'Introduction', t: '…To alleviate the growing workload of scientists, simplify compliance with standard operating procedures (SOPs), and ensure consistency of data sets, automation is a proven concept and a key milestone on the evolution towards autonomous research. Autonomous catalyst discovery means that a target variable, such as a rate or selectivity in a particular catalysed reaction, can be optimized independently and adapted in multiple feedback loops without human control or detailed programming.…' },
    { s: 'Introduction', t: '…To make this possible, the first step is the automation of all work steps in catalysis research, from materials synthesis to testing and characterization, including, for example, data evaluation, consideration of safety requirements or the supply of chemicals, which is a challenge given the complexity of heterogeneous catalysis.…' }
  ] },
  { p: 45, items: [
    { s: 'Types, Examples And Significance Of SDLs', t: '…The second major published example of a self-driving cloud lab was a collaboration between the Gomes group at Carnegie Mellon University and Emerald Cloud Lab (ECL), one of, if not the, largest commercial cloud laboratories in the world. This publication describes Coscientist, an AI chemist that designs and plans complex experiments and generates ready-to-execute code in Symbolic Lab Language, the lingua franca of ECL and the cloud lab they built for Carnegie Mellon University.…' },
    { s: 'Safety And Security', t: '…If this controlling AI became set itself towards a malevolent objective and could defeat the cloud laboratory\u2019s cybersecurity controls, the rogue AI could rewrite the code for multiple customer experiments to create harmful products or dangerous conditions. Such an "SDL as a service" has yet to be made available to the public; however, Emerald Cloud Lab has declared its intention to implement AI within its environment and collaborated on the recent publication describing Coscientist, an AI system that "autonomously designs, plans, and performs complex [chemistry] experiments".…' },
    { s: 'Self-Driving Cloud Labs', t: '…Being partially based on the GPT-4 large language model from OpenAI, Coscientist features impressive chemical and general reasoning capabilities and an internet searching module that "significantly improves on synthesis planning".…' }
  ] },
  { p: 22, items: [
    { s: 'Discussion', t: '…These innovations help minimise human bias, accelerate research cycles, and reduce variation introduced by human error and incomplete recording of experimental protocols, environmental conditions, and other subtle factors that can influence outcomes. In this automated paradigm, algorithms design experiments, robots execute protocols, and the results are all automatically analysed, thus enabling exploration of vast experimental spaces beyond human throughput.…' },
    { s: 'Methods', t: '…APO was designed to record hypotheses about genotype–phenotype relations, and statements generally have four components: (1) the type of mutant; (2) the phenotype; (3) a qualifier on the phenotype (e.g. "increased"); and (4) the experiment type. The implicit definition of these qualifiers is for a mutant with respect to a wild-type strain.…' },
    { s: 'Introduction', t: '…Hallucinations and inconsistent outputs are still significant challenges, even when augmented with sophisticated reasoning frameworks. Despite the increasingly widespread use of LLMs in scientific discovery, this issue is seldom properly addressed. Additionally, despite growing reliance on LLMs for hypothesis generation, these hypotheses are rarely subjected to rigorous evaluation, and the underlying data often remain siloed within individual labs rather than being shared with the scientific community, undermining collective progress.…' }
  ] },
  { p: 41, items: [
    { s: 'Introduction', t: '…As with all tools that allow us to better manipulate biology, future advanced AI models have the potential to be misused or misapplied, and these biosecurity risks have been publicly noted by scientists and model developers. Baker and Church note that AI protein design models are "vulnerable to misuse and the production of dangerous biological agents" while Boiko and colleagues include a security supplement in which they state that they "strongly believe that guardrails must be put in place to prevent … dual use of large language models" for autonomous completion of chemical and biological synthesis protocols.…' },
    { s: 'Introduction', t: '…For example, there are efforts to enable access to leading open-source protein and molecular design tools using directly integrated AI chatbot interfaces, also termed "copilots". Researchers and companies are seeking to develop autonomous or semi-autonomous AI agents capable of conducting science. Some AI tools provide assistance to novices in completing complex research tasks (termed AI "uplift"), while others aim to eliminate humans-in-the-loop entirely.…' },
    { s: 'Introduction', t: '…LLMs, biological AI models, and integrations of the two, can also interface with AI-enabled autonomous laboratory environments. These capabilities further reduce the time, expertise, and equipment required to synthesize pathogens, and suggest the possibility of end-to-end or "full stack" AI tool development in this domain.…' }
  ] },
  { p: 46, items: [
    { s: 'Introduction', t: '…Large language models (LLMs) have emerged as reasoning engines capable of intelligent reasoning and planning over complex tasks. Recent works have explored leveraging LLMs as intelligent agents, using natural language as an interface for taking actions and observing results. By pairing LLM\u2019s reasoning capabilities with computational tools for drug discovery, we envision building a digital twin of the medicinal chemist, capable of navigating the complexities of the drug discovery process.…' },
    { s: 'Related Work', t: '…For drug discovery, Coscientist uses LLMs to perform web search, conduct technical documentation, program, and operate physical hardware modules to plan and control chemical synthetic experiments. It demonstrates the viability of LLM agents equipped with both physical and computational tools to act as self-driving laboratories for organic chemistry.…' },
    { s: 'Limitations', t: '…This serves as a trade-off between scope (lack of benchmarks) and substance (focusing on clinically relevant targets). This follows the example of related LLM agent works, which have used similarly small benchmarks for initial demonstrations of agent capabilities on complex tasks. Future work will include an expansion of this dataset and additional benchmarking.…' }
  ] },
  { p: 51, items: [
    { s: 'Introduction', t: '…Simultaneously, large language models (LLMs) have gained attention in chemical research, offering novel interfaces with chemical data and assisting chemists, particularly those less experienced with digital tools, in customizing their digital workflows through intuitive natural language prompts.…' },
    { s: 'Benchmarking LLMs Auto Code Generation', t: '…Finally, in task 4, LLMs were tasked with generating executable scripts for liquid handling robots. This task demonstrated the practical applicability of LLM-generated code in automating physical processes in the lab, consistent with the previous literature findings. Furthermore, we introduced a "self-reflection" mode in the benchmarking process and evaluated the codes generated with or without this model.…' }
  ] },
  { p: 33, items: [
    { s: 'AI And Large Language Models For Scientific Discovery', t: '…AlphaFold-2 stunned the structural-biology community by predicting protein folds across whole proteomes with near-experimental accuracy, notably awarded recently the Nobel Prize in chemistry. Autonomous chemistry has taken a parallel leap: Boiko et al. combined a GPT-4-driven planner with robotic synthesis and analysis, demonstrating that a language-model agent can design, execute and interpret multi-step reactions without human intervention, effectively turning hypothesis generation and testing into a closed computational loop.…' },
    { s: 'AI And Large Language Models For Scientific Discovery', t: '…An example are AI tools developed to optimize chemical reactions in pharmaceutical research, significantly reducing trial and error. AI can suggest new and simpler experimental paths based on data from previous experiments. This predictive capability ensures that experiments are not only well-designed but also more likely to yield valid and reproducible results.…' },
    { s: 'Self-Driving Laboratories And Autonomous Experimentation', t: '…Give the agent a desired product and safety constraints; it searches reaction databases, proposes synthetic routes, orders reagents, schedules equipment time, executes experiments and analyses results, iteratively refining conditions until yield targets are met. In 2023 such systems were rudimentary demonstrations; by 2024 Nature reported a fully autonomous synthesis of twenty-nine organosilicon compounds, eight of which were previously unknown.…' }
  ] },
  { p: 28, items: [
    { s: 'Hypothesis Generation And Search Over Scientific Spaces', t: '…They can also find domain-specific entities and relationships and provide mechanistic narratives or qualitative design rationales. Recent agentic systems that link LLMs to chemistry and materials tools demonstrate that these models can suggest reaction pathways, enumerate viable synthetic routes, and advocate for experimental parameter sweeps by utilizing patterns found in the literature and outputs from external tools.…' },
    { s: 'Experiments And Simulation Planning', t: '…Ad hoc filtering is typically used to deal with practical problems like scheduling, equipment failures, maintenance windows, or safety limitations, instead of using a systematic decision-theoretic formulation. LLM-based planners can create flexible protocols and coordinate tools, but they are still restricted by hallucinations, poor calibration of uncertainty, and inadequate guarantees that they will follow safety or physical rules.…' },
    { s: 'Experiments And Simulation Planning', t: '…Autonomous research frameworks utilizing general-purpose LLMs have demonstrated the capacity to strategize and implement multi-step experimental campaigns, encompassing the selection of conditions, coordination of robotic platforms, and iterative enhancement of protocols. Recent research assesses LLM agents for the automation of particular experimental modalities, like atomic force microscopy, underscoring both the potential and the existing fragility of language-model-driven laboratory control.…' },
    { s: 'AI Models', t: '…Beyond text mining and property prediction, LLMs are beginning to function as AI chemists. Coscientist, powered by GPT-4, exemplifies this trend by autonomously designing, planning, and executing complex experimental workflows through an integrated platform that includes internet and document searches, code execution, and experimental automation. Its capabilities were demonstrated by successfully optimizing several research tasks, including a palladium-catalyzed cross-coupling reaction.…' },
    { s: 'Applications To Molecular Design', t: '…In addition, lots of intelligent robotic systems and autonomous laboratories have been established, significantly accelerating the pace of material innovation.…' }
  ] },
  { p: 44, items: [
    { s: 'Introduction', t: '…Large language models and multi-agent systems offer a possible route toward organizing such long-horizon scientific workflows. Recent AI-scientist and tool-augmented discovery systems have demonstrated capabilities in hypothesis generation, code execution, autonomous experimentation, and scientific reporting. However, existing systems mainly operate in domains where experiments are code-level, laboratory-tool-based, or data-analysis-oriented.…' },
    { s: 'LLM Agents And AI Scientists', t: '…It involves hypothesis formulation, experiment design, execution, evidence assessment, and qualified conclusions under uncertainty. Recent AI-scientist systems and autonomous discovery frameworks have explored this direction in machine learning, chemistry, and materials-related settings. However, their experimental environments are typically code-level, laboratory-tool-oriented, or data-analysis-based.…' },
    { s: 'Scientific Report', t: '…AI Scientist  ChemCrow  Coscientist  EarthLink  Earth-Agent  TianJi-Environ.…' }
  ] },
  { p: 42, items: [
    { s: 'Introduction', t: '…Recent scientific-agent systems have explored chemistry, molecular dynamics, computational fluid dynamics, finite-element and multiphysics modeling, reservoir simulation, and other simulator-centered workflows. Many of these systems build simulator-specific agent loops from scratch, including custom planning, tool calling, retry logic, and termination handling.…' },
    { s: 'Related Work', t: '…Domain-application systems include ChemCrow and Coscientist for chemistry, CellVoyager for single-cell analysis, and The AI Scientist for end-to-end ML research. Closer to our setting are agents for scientific simulators: OpenFOAM-oriented computational fluid dynamics agents, molecular-dynamics agents, finite-element/mechanics agents, and reservoir-simulation agents.…' },
    { s: 'Related Work', t: '…Recent agent work treats capability as an iterative loop of planning, execution, feedback, and refinement that externalises experience into memory, search states, or revised plans. A particularly active subfield, which treats the agent\u2019s own scaffolding as a learnable object, has shown promising results on core AI benchmarks (coding, terminal navigation, math).…' }
  ] },
  { p: 25, items: [
    { s: 'Introduction', t: '…Language models have been used for scientific literature synthesis, hypothesis generation, protocol construction, code development, data analysis and manuscript preparation. When connected to simulators, robotic laboratories and scientific instruments, agents can additionally execute experimental procedures, optimize control parameters and update decisions from measured outcomes. Multi-agent architectures further distribute these functions across specialized roles.…' },
    { s: 'A Socratic Multi-Agent Architecture', t: '…The supervisor can veto unsafe actions, correct hardware-incompatible plans or annotate uncertain interpretations, while all agent states and experimental outcomes are logged. This supervision is used as a safety and quality gate rather than as a replacement for the agent\u2019s planning, execution and analysis loop.…' },
    { s: 'Discussion', t: '…Adaptive microscopes, scattering-based imaging systems, photonic processors, autonomous synthesis platforms and high-throughput materials-characterization systems all require decisions under partial observability, instrument drift and competing mechanistic interpretations. In such environments, the limiting factor is often not whether an agent can issue a command to an instrument, but whether it can determine what the resulting measurement means.…' }
  ] },
  { p: 30, items: [
    { s: 'Main', t: '…Large language models are reshaping how scientists interact with data. From autonomous chemical synthesis to mathematical discovery and multi-agent nanobody design, AI systems are increasingly capable of executing complex research workflows with minimal human intervention. In computational biology, domain-specific foundation models and agents have been developed for single-cell multi-omics and autonomous transcriptomics analysis.…' },
    { s: 'Supplementary Materials', t: '…The module supports three sorting backends and implements a multi-stage curation workflow that can filter units based on firing rate, ISI violation ratio, signal-to-noise ratio, spike count, and waveform spatial consistency. A dedicated skill wraps this module for agentic access, extending the text-to-analysis framework from the analysis stage back to the data preprocessing stage.…' },
    { s: 'Supplementary Materials', t: '…Because SpikeInterface provides recording extractors for a wide range of electrophysiology file formats, including Open Ephys, Intan, Neuralynx, Plexon, Blackrock, and others, this indirectly extends the module\u2019s format support to the full SpikeInterface ecosystem.…' }
  ] },
  { p: 70, items: [
    { s: 'Integration With Robotics Toward Self-Driving Laboratories', t: '…Foundational breakthroughs in broader chemistry domains have validated the feasibility of full autonomy. Boiko et al. unveiled Coscientist, a GPT-4 driven system that autonomously plans and executes palladium-catalyzed coupling reactions. This work verified the LLM-as-optimizer paradigm in wet chemistry.…' },
    { s: 'Conclusion, Challenges And Outlook', t: '…Finally, we have reached the frontier of autonomous agency. LLMs now act as cognitive co-scientists capable of reasoning, planning, and utilizing tools. This trajectory highlights a decisive shift.…' }
  ] },
  { p: 72, items: [
    { s: 'Introduction', t: '…This approach should combine data-driven methods, biologically informed modeling, and advanced tools such as Large Language Models (LLMs) to better understand and predict the behavior of complex biological systems across multiple scales. LLMs can decompose high-level tasks into sub-goals, reason through problems step-by-step in a manner similar to the human chain of thought, and plan sequential actions to achieve defined objectives.…' },
    { s: 'Reasoning Of The Framework', t: '…Operationally, the Full-Body AI Agent routes data perception to Coscientist for technical documentation and assay protocol parsing, to AI Scientist for literature ingestion and dataset onboarding, to SpatialAgent for multimodal tissue images and spatial omics, and to TxAgent adapters for structured clinical and biomolecular endpoints.…' }
  ] },
  { p: 27, items: [
    { s: 'Introduction', t: '…This approach paves the way for a self-driving laboratory, establishing a feedback loop between computational predictions and automated experiments.…' },
    { s: 'Discussion', t: '…In the era where combinatorial chemistry, self-driven laboratories, and feedback loops between models and experimental measurements can be implemented to discover the best combinations of reactants for the desired target, I have provided sufficient evidence to push the current paradigm forward.…' },
    { s: 'Introduction', t: '…Researchers are making significant strides toward automated scientific discovery. Notable examples include the fully AI-driven chemist developed by Zhu et al., as well as the AI-based chemical experimentation system named Coscientist. In addition to academic researchers, leading technology companies such as OpenAI, Meta, Microsoft, and IBM are also investing in AI-driven scientific research.…' },
    { s: 'Autonomous Scientific Discovery Agents', t: '…For example, an agent can first search relevant protocols, then generate an experimental plan, call external tools or code interfaces, and finally coordinate laboratory equipment to complete a multi-step research task. Some advanced systems exemplify this trend, such as Coscientist and ChemCrow. Coscientist adopts a modular architecture in which a planner powered by GPT-4 interacts with external tools to support internet and document search, code execution, and experimental automation.…' }
  ] },
  { p: 7, items: [
    { s: 'AI And Generative AI To Develop Advanced Surfactants', t: '…The integration of machine learning, deep learning, and generative artificial intelligence technologies represents a step forward in the development of more efficient, sustainable, and performance-enhancing surfactant development. These tools have the potential to advance the way surfactant structures are discovered, designed, and optimized, offering opportunities to tailor molecules for specific applications.…' },
    { s: 'Generative AI', t: '…Recently large language models (LLM) and generative pretrained transformer (GPT) models have been proposed as a tool to optimize chemical synthesis and design new polymer molecules. The body of knowledge that is being created in different disciplines, mainly the pharmaceutical field, will allow the use of deep learning and generative AI in other applications.…' },
    { s: 'Introduction', t: '…In particular, artificial intelligence (AI) and machine learning (ML) provide useful tools for analyzing experimental data, exploring large synthesis parameter spaces, and managing the intricate couplings among these thermodynamic and kinetic variables. By learning quantitative relationships between processing parameters and material outcomes from limited and noisy datasets, AI-based models can assist in catalyst screening, process optimization, and experimental design.…' },
    { s: null, t: '…Large language model (LLM) enabled a scientific agent framework integrating web search/browsing, code execution, planning, documentation, and laboratory automation, illustrating how tool-augmented LLMs can coordinate multi-step reasoning and experimental workflows.…' }
  ] },
  { p: 15, items: [
    { s: 'Introduction', t: '…Guidelines have also been published for standardizing LLMs and protocols to speed up synthesis planning in heterogeneous catalysis. Researchers are utilizing AI to formulate reaction arrays in pharmaceutically relevant organic reactions, such as Suzuki, Buchwald–Hartwig, or other Pd catalyzed cross-coupling reactions. Clinical chemists have employed ChatGPT for predicting hemoglobinopathy from clinical results with 76% accuracy.…' },
    { s: 'Introduction', t: '…In this study, we chose four recently published scientific papers from multiple analytical chemistry subfields: spectroscopy, bioimaging, chromatography, and electroanalytical chemistry.…' },
    { s: 'Introduction', t: '…Remarkably, an LLM-containing architecture that integrates these functions with robotic equipment manipulation has achieved self-driven organic syntheses and refinement of cross-coupling reaction conditions. As automated chemical research becomes increasingly common, it is plausible that college chemical education may eventually involve training students to interact with chemistry-specific LLM systems.…' },
    { s: 'Introduction', t: '…Indeed, LLM-containing systems have demonstrated the ability to construct lengthy summaries of user-defined chemical research collections, while GPTs have been used to curate synthetic parameters for metal–organic frameworks (MOFs) from precompiled literature. Synthetic conditions for MOFs have also been optimized via LLM interfaces that possess basic experimental design and analysis capabilities.…' }
  ] },
  { p: 23, items: [
    { s: 'Introduction', t: '…In chemistry, particularly reticular chemistry, there is significant potential for LLMs to assist in answering complex scientific queries and to enhance research productivity by automating routine yet important tasks. However, achieving truly effective, chemistry-specific LLM agents requires specialized training data that are well-structured, contextually accurate, and comprehensible to these models.…' },
    { s: 'Introduction', t: '…Prior research from leading organizations such as OpenAI has demonstrated that reinforcement learning with human feedback (RLHF), a process involving iterative interactions between humans and LLMs, where human evaluators validate and provide corrective feedback on LLM-generated outputs by labeling Question and Answer (Q&A) pairs, can substantially improve model accuracy and responsiveness.…' },
    { s: 'LLMs And Multimodal Models For Chemistry', t: '…Fully autonomous chemical research may be possible with LLMs planning the high-level experimental steps (i.e. a sequence of action primitives) and autonomous lab robots executing the planned actions.…' },
    { s: 'AI For Robotics In Chemistry', t: '…The Coscientist represents another example, which can autonomously conduct complex tasks like synthesizing molecules, optimising reactions, and programming robotic systems to perform specific experimental protocols. Equipped with a computational brain, machine reading capabilities, and mobile robotic modules, an AI-Chemist seamlessly integrates literature-based knowledge extraction, automated synthesis, characterisation, and performance testing.…' }
  ] },
  { p: 29, items: [
    { s: 'Introduction', t: '…LLMs inherently possess extensive chemical knowledge, and recent advancements have focused on extracting and applying this knowledge for predictive and optimization tasks using natural language guidance. Furthermore, after fine-tuning, LLMs can perform as good or better than chemical language models trained solely on chemical representations, all while requiring less data.…' },
    { s: 'Discussion', t: '…Motivated by recent advances in LLMs for chemistry, we aim to leverage data-efficient supervised fine-tuning (SFT) to transform the general-purpose Meta Llama 3 into an LLM-based generator capable of proposing synthesizable molecules and deducing synthetic routes for target molecules or their close analogs.…' },
    { s: 'Emerging AI/ML Methodologies', t: '…The second refers to large language models (LLMs) trained on extensive chemical, molecular, or materials corpora. Although both groups of models share underlying principles such as large-scale training, generalization, and cross-domain transferability, they differ fundamentally in their objectives, data modalities, and modes of interaction with chemical problems. While LLMs themselves still perform poorly in generating valid molecules or reactions from scratch, they are rapidly improving at interpreting, contextualizing, and reasoning about chemical information.…' },
    { s: 'Emerging AI/ML Methodologies', t: '…LLMs with specialized tools have shown promise for coding, processing of chemical information, and controlling lab automation.…' }
  ] },
  { p: 38, items: [
    { s: 'Structured Data Extraction Workflow', t: '…They have shown promise in tasks as varied as simulating human behavior, playing Minecraft, molecule design, and autonomously performing chemical reactions. As a result of the several reasoning cycles that the agents perform, they often outperform vanilla LLMs. But what advantages can they present in extracting data?…' },
    { s: 'Structured Data Extraction Workflow', t: '…Since agents are supposed to interact with their environment, giving them access to computer systems or even laboratories requires additional safety precautions.…' },
    { s: 'Introduction', t: '…Like other computer programs, but unlike human scientists, LLMs are inexhaustible, able to run all day, every day, which is useful not just in automated digital discovery workflows, but also for setups like automated laboratories or pilot lines. They are typically more flexible and adaptable than traditional computer programs, making them more effective when run continuously.…' },
    { s: 'Capabilities Of LLMs In Research', t: '…"Coscientist" used LLMs as a coordinator to design, plan and execute chemical research. It can call web search APIs, generate and execute Python code, search documentation, interact with and write code for physical hardware.…' }
  ] },
  { p: 50, items: [
    { s: 'Methods', t: '…The MFIA impedance analyzer connects directly to the computer via USB, while the Alpha-A spectrometer and the Keithley sourcemeter communicate through the National Instruments GPIB-USB-HS interface. To ensure safety, particularly in light of potential LLM hallucinations, the LLM generates only control instructions, which are then executed by pre-written API programs. This approach simplifies the process and ensures safety.…' },
    { s: 'Introduction', t: '…With the emergence and development of generative AI and large language models (LLMs), scientists have begun to build intelligent agents or automated research assistants to assist people in completing complex tasks. In the field of chemical research, scholars have proposed and developed intelligent agents such as Coscientist and ChemCrow. These types of agents are capable of performing chemical synthesis planning and corresponding physical operations.…' },
    { s: 'Main', t: '…These initiatives encompass a wide range of technological advancements, from programmable Chemputers for molecular synthesis to mobile robotic chemists capable of conducting multi-step material synthesis, characterization, and testing. Additionally, advancements include autonomous reaction optimization driven by large language models (LLMs) and AI-coordinated self-driving labs that facilitate asynchronous, cloud-based, and delocalized closed-loop discovery of functional molecules.…' },
    { s: 'Main', t: '…The rapid development of sophisticated automation systems, including high-throughput platforms, dexterous robotic arms, mobile robots, and automated experimental stations, is propelling the continuous evolution of autonomous chemistry laboratories. These advancements not only significantly shorten the time from hypothesis formation to experimental validation but also expand researchers\u2019 perspectives and experimental boundaries.…' }
  ] }
];

// The agent's synthesis — streamed into the module (and mirrored in the thread).
// [[i]] marks a reference to a citing paper: i indexes GROUPS.
export const SUMMARY = [
  '<p>Across the corpus, this paper is cited less as a result to build on than as a <em>proof of possibility</em>: the moment an LLM agent was shown to plan, execute and interpret a real wet-lab experiment end to end. Surveys reach for it and ChemCrow together as the pair that opened the field [[1]] [[8]], and later systems position themselves relative to it rather than against it.</p>',
  '<p>Three roles recur. <strong>Precedent for architecture</strong>, the Planner / web search / docs search / code execution / automation decomposition is reproduced almost verbatim when new agents motivate their own module diagrams [[10]] [[12]]. <strong>Evidence for capability</strong>, the Suzuki and Sonogashira couplings are the canonical citation for "an agent did chemistry", including in reviews of drug discovery [[0]] and self-driving labs [[16]]. <strong>Anchor for critique</strong>, safety and dual-use papers cite the same work for its own security supplement, reading the guardrail discussion as an admission that the capability is uncomfortable [[3]] [[18]].</p>',
  '<p>The disagreement is narrow but real. Several papers argue the system remains <em>disembodied</em> or brittle: it plans well but still leans on humans for physical execution [[2]], hands off partial results poorly in multi-agent settings [[4]], and has only been demonstrated on well-studied reactions where literature recipes already exist [[3]]. A closed-loop catalysis study frames its whole contribution as the test this paper did not run, LLM versus human expert over a long-horizon noisy campaign [[6]].</p>',
  '<p>Nothing in the corpus contests the reported results themselves. What is contested is the scope of the claim: whether "autonomous" survives contact with problems that have no precedent in the training data.</p>'
];

export const SUMMARY_FOOT = 'Synthesized from 145 passages across 35 citing papers in this corpus';
